- name: Install mongodb
  apt:
    name: mongodb
    state: present
    update_cache: yes
  retries: 5
  delay: 20
  tags: install

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  tags: install

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags: install

- name: Enable mongodb service
  systemd:
    name: mongodb
    enabled: yes
  tags: install
