- name: Install Python
  hosts: all
  gather_facts: true

  tasks:
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python_result

    - name: Install Pyhon use raw module
      raw: apt install -y python
      become: true
      when: check_python_result.rc != 0
