---
- name: Install base for database server
  hosts: all
  become: true
  tasks:
    - name: Install mongodb
      apt:
        name: mongodb
        state: present
        update_cache: yes
      retries: 5
      delay: 20

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Enable mongodb service
      systemd:
        name: mongodb
        enabled: yes
