---
- name: Install base for application deploy
  hosts: all
  become: true
  tasks:
    - name: Install packages for app base
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'ruby-full', 'ruby-bundler', 'build-essential', 'git']
        state: present
        update_cache: yes
      retries: 5
      delay: 20

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
